version: 1 # Sourcery schema requires literal 1

ignore:
  - **/node_modules/**
  - **/.next/**
  - **/.turbo/**
  - **/dist/**
  - **/coverage/**
  - **/.gradle/**
  - **/build/**
  - **/data_samples/**
  - **/.github/**

options:
  lint: true
  test_command: ""
