version: '1'

ignore:
  - '**/node_modules/**'
  - '**/.next/**'
  - '**/.turbo/**'
  - '**/dist/**'
  - '**/coverage/**'
  - '**/.gradle/**'
  - '**/build/**'
  - '**/data_samples/**'
  - '**/.github/**'
